# 站点配置

# 导入主题
theme: jekyll-theme-chirpy

# 网页语言设置 › http://www.lingoes.net/en/translator/langcode.htm
# 如果与 `_data/locales` 文件夹中的某个文件名相同，布局语言也会相应改变，
# 否则，布局语言将使用默认值 'en'。
lang: zh-CN

# 时区设置 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: PBA # 主标题

tagline: PoweredByAlgo # 显示为副标题

description: 一个简洁、响应式且功能丰富的Jekyll技术写作主题

# 填写您网站的协议和主机名
# 例如 'https://username.github.io'，注意结尾不要带 '/'
url: "https://poweredbyalgo.top"

github:
  username: poweredbyalgo # 更改为您的 GitHub 用户名

twitter:
  username: night2eight # 更改为您的 Twitter 用户名

social:
  # 更改为您的全名
  # 将作为帖子的默认作者和页脚中的版权所有者显示
  name: PoweredByAlgo
  email: poweredbyalgo@gmail.com # 更改为您的邮箱地址
  links:
    # 第一个元素作为版权所有者的链接
    - https://twitter.com/night2eight # 更改为您的 Twitter 主页
    - https://github.com/poweredbyalgo # 更改为您的 GitHub 主页
    # 取消注释以下行以添加更多社交链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 站点验证设置
webmaster_verifications:
  google: # 填写您的 Google 验证代码
  bing: # 填写您的 Bing 验证代码
  alexa: # 填写您的 Alexa 验证代码
  yandex: # 填写您的 Yandex 验证代码
  baidu: # 填写您的 Baidu 验证代码
  facebook: # 填写您的 Facebook 验证代码

# ↑ --------------------------
# `jekyll-seo-tag` 设置结束

# 网站分析设置
analytics:
  google:
    id: G-9JB7YG36BB
  goatcounter:
    id: poweredbyalgo # 替换为你的 GoatCounter ID
  umami:
    id: # 填写您的 Umami ID
    domain: # 填写您的 Umami 域名
  matomo:
    id: # 填写您的 Matomo ID
    domain: # 填写您的 Matomo 域名
  cloudflare:
    id: # 填写您的 Cloudflare Web Analytics 令牌
  fathom:
    id: # 填写您的 Fathom 站点 ID

# 页面浏览设置
pageviews:
  provider: #goatcounter # 启用 GoatCounter 页面浏览统计

# 主题配色方案设置
#
# 注意：留空将默认跟随系统主题设置，
# 在侧边栏左下角会有切换按钮在深色和浅色主题间切换
#
# 可用选项：
#
#     light — 使用浅色主题
#     dark — 使用深色主题
#
theme_mode: # [light | dark]  不配置就可自由选择，默认跟随系统主题

# 媒体资源的 CDN 端点
# 注意：一旦设置，CDN 网址将被添加到所有以 '/' 开头的媒体资源路径
# （站点头像、帖子图片、音频和视频文件）
#
# 例如 'https://cdn.com'
cdn:

# 侧边栏头像，支持本地或 CORS 资源
avatar: /assets/img/avatar.jpg

# 用于 SEO `og:image` 元标签的站点范围社交预览图片 URL
# 可以通过自定义的 `page.image` 在前置内容中覆盖
social_preview_image: # 字符串，本地或 CORS 资源

# 布尔类型，帖子中目录的全局开关
toc: true

comments:
  # 帖子评论系统的全局开关。留空表示禁用
  provider: giscus # [disqus | utterances | giscus]
  # 提供商选项如下：
  disqus:
    shortname: # 填写 Disqus 简称 › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances 设置 › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus 选项 › https://giscus.app
  giscus:
    repo: poweredbyalgo/poweredbyalgo.github.io # <gh-username>/<repo>
    repo_id: R_kgDOP5bNog
    category: Announcements
    category_id: DIC_kwDOP5bNos4CwWHG
    mapping: pathname # 可选，默认为 'pathname'
    strict: 0 # 可选，默认为 '0'
    input_position: top # 可选，默认为 'bottom'
    lang: zh-CN # 可选，默认为 `site.lang` 的值
    reactions_enabled: 1 # 可选，默认为 '1'
    theme: preferred_color_scheme # 跟随系统主题设置
    loading: lazy
    crossorigin: anonymous

# 自托管静态资源，可选 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # 布尔值，留空表示 false
    # 指定 Jekyll 环境，留空表示两者都适用
    # 仅在 `assets.self_host.enabled` 为 'true' 时生效
    env: # [development | production]

pwa:
  enabled: true # PWA 功能（可安装）选项
  cache:
    enabled: false # 临时禁用PWA缓存以解决图片更新问题
    # 这里定义的路径将被排除在 PWA 缓存之外
    # 通常是另一个与当前网站共享相同域名的网站的 `baseurl`
    deny_paths:
      # - "/example"  # 匹配 `<SITE_URL>/example/*` 的 URL 不会被 PWA 缓存

paginate: 10

# 您网站的基础 URL
baseurl: ""

# ------------ 以下选项不建议修改 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge 选项 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # 空字符串表示项目中的所有文件
      type: posts
    values:
      layout: post
      comments: true # 在帖子中启用评论
      toc: true # 在帖子中显示目录列
      # 除非您有足够的信心
      # 更新此项目中所有其他帖子链接的代码，否则不要修改以下参数
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # 参见 `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - "_posts/*/pic/*.png"
  - "_posts/*/pic/*.jpg"
  - "_posts/*/pic/*.jpeg"
  - "_posts/*/pic/*.gif"
  - "_posts/*/pic/*.bmp"
  - "_posts/*/pic/*.svg"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-sitemap  # 确保这行存在，无注释

sitemap:
  changefreq: always  # 页面更新频率（always/daily/weekly/monthly/yearly/never）
  priority: 1.0       # 页面优先级（0.0-1.0，首页建议设1.0）